---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: {{ default .Release.Namespace .Values.clusterName }}
spec:
  monitoring:
    enabled: {{ .Values.monitoring.enabled | default false }}
{{- if .Values.monitoring.externalMgrEndpoints }}
    externalMgrEndpoints:
{{ toYaml .Values.monitoring.externalMgrEndpoints | indent 6 }}
{{- end }}
{{- if .Values.monitoring.externalMgrPrometheusPort }}
    externalMgrPrometheusPort: {{ toYaml .Values.monitoring.externalMgrPrometheusPort }}
{{- end }}

{{ toYaml .Values.cephClusterSpec | indent 2 }}
